### ISSUE TITLE
Menu button clipping

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/Modoki-Firefox#8]
![image](https://user-images.githubusercontent.com/11209477/223562285-26ca5133-f1a3-4003-a41c-4fc74d25cf08.png)

There appears to be a clipping issue, with the menu button appearing to get cut off on the right-hand side. So far experienced in Xubuntu 22.04, and in the Gitpod instance.

**Comment by soup-bowl** [comment]
I find that setting:

```css
#TabsToolbar .toolbar-items,
#TabsToolbar-customization-target {
	width:100%;
}
```

Shows the full length of the tab bar again, like so:

![image](https://user-images.githubusercontent.com/11209477/226143117-4a4990f9-aa8c-4315-b87e-f1352dd17c55.png)

But I cannot seem to achieve the same with the navbar. I've also tried setting this to higher up elements, without success.
